### ISSUE TITLE
"Open in Bizman" inside building opens own businesses list instead of current business data

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#120]
Alpha 4 - Build 49

When outside of the building and hover over the building menu appears which contains the "Open in Bizman" button, this works, however, when you are in the building the "Open Bizman" button on the right of the screen above the phone just opens a blank bizman page instead of the stores.

**Comment by Gerwanese** [comment]
It's actually opening the same BizMan view that also opens from the button on the phone itself. It's showing an empty screen if you don't own any business yet, otherwise a list of your businesses.
I'd consider this a bug anyways since you're clicking "Open in BizMan" for a specific business, so you shouldn't see the overview of your own businesses but indeed the data for the selected business.

https://user-images.githubusercontent.com/17579552/120375212-d11f7d80-c31a-11eb-8f29-5f76deeeba66.mp4

**Comment by jhovgaard** [comment]
Fixed in build 51
