### ISSUE TITLE
Clothes racks block way even beyond their borders

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#181]
Build 55

I can't walk between the clothing racks although there's plenty of space. Also when picking up the clothes racks, the green outline shows that there's still a gap of two squares in between.

https://user-images.githubusercontent.com/17579552/121823919-9b7a7d00-cca8-11eb-9eb7-3e26e9e1b5c2.mp4

**Comment by jhovgaard** [comment]
Fixed by reducing player navmesh radius to 35 cm. Build 75

**Comment by Gerwanese** [comment]
It's much better now, but with only one square in between it's still impossible to get through.

[Build75-Clothing.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778539/Build75-Clothing.txt)


https://user-images.githubusercontent.com/17579552/124790777-bfe61400-df4b-11eb-997f-7df37239b2f1.mp4

**Comment by jhovgaard** [comment]
It just became a rather complex issue, as I can't reduce the player navmesh radius any further. I guess the real problem is that the grid makes you believe that 1 free cell means that it's "clear". We should increase the grid's cell size to fit the player radius and then update all objects to fit the new grid. Unfortunately, it's a massive amount of work.

Let's close the ticket for now, but add comments every time a player reports the bug. Later on, we can see if it's worth putting in the work.
