### ISSUE TITLE
When you have fresh food on a handtruck and you eat it the box remains on the handtruck empty

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions-public#293]
Build 75.
Might be fixed by fixing Bug #83 
![Big Ambitions 7_7_2021 2_32_33 PM](https://user-images.githubusercontent.com/85610694/124759910-789e5a00-df30-11eb-9418-9f99e26bd400.png)

**Comment by Gerwanese** [comment]
Confirmed. The box even stays after adding another new box onto the hand truck.
Issue might be solved already with the fix for #285 - have to double check in build 76.

[Build75-SchrodingersBox.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778395/Build75-SchrodingersBox.txt)

https://user-images.githubusercontent.com/17579552/124786689-35e87c00-df48-11eb-9464-58cfaee6c132.mp4

**Comment by Gerwanese** [comment]
As expected, issue is fixed already with the changes for #285. Box is not edible anymore in build 76.
