### ISSUE TITLE
EconoView: Purchase cost of salad not registered

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#359]
Build 120

The purchase price of salad is not registered in the "Resources" section of EconoView.

[Build106-EconoViewBugs.txt](https://github.com/hovgaardgames/bigambitions-public/files/6903486/Build106-EconoViewBugs.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127562287-f06649af-32db-49f7-9cfc-bede3e3db34f.png)

**Comment by jokoho48** [comment]
i believe this was a old bug where Salad did have a wholesale price of 0(or got rounded to 0) and due to that being saved in the savegame this save game is always showing that. i could not reproduce in a new savegame that is why i am closing this issue. if it happens again we can always reopen it. 😄
