### ISSUE TITLE
Doing objective in wrong order

### ISSUE THREAD

**Issue by LucaFeger** [hovgaardgames/bigambitions-public#8]
If you don't stick to the order of the objectives (in my case doing the fundamental business course as the first objective), you need to work a day before the objectives are fulfilled.

**Comment by Gerwanese** [comment]
Could verify, objectives in wrong order are not registered.
Also objectives that are already met (e.g. already having a mop in the store) are not registered once the objectives show up.

**Comment by jhovgaard** [comment]
Fixed in build 54

**Comment by Gerwanese** [comment]
Mostly fixed, however:

- 15.000 bank loan: not checked if you already have several loans (even >15000). It has to be a new one of 15.000 or more.
- Buying a fridge: buying the fridge was not registered (2nd screenshot), although it's registered as placed and filled.
- Buying a mop: Not registered, but once I used the already existing mop, the "buy a mop" task also got checked.
- Interview 10 citizen: Not registered, although interview lite app shows 21 interviews done (see attached video). One more interview will trigger the task to be completed.

That's all I could find after redoing the whole tutorial.

![grafik](https://user-images.githubusercontent.com/17579552/121821829-d1fdcb00-cc9b-11eb-8e6a-bcac1dd5c7de.png)

![grafik](https://user-images.githubusercontent.com/17579552/121822239-52bdc680-cc9e-11eb-955f-5f12f33a82e4.png)

https://user-images.githubusercontent.com/17579552/121823219-19885500-cca4-11eb-9038-59a1166ed83c.mp4

**Comment by jhovgaard** [comment]
@Gerwanese Any chance you have savegame files for the scenarios above? Would save me quite some time :D

**Comment by Gerwanese** [comment]
I just created the savegames for you. :)
Attached in the zip file you find all reports (JSON is not allowed for attachment and I was afraid in case of txt, the encoding might be changed).

1. Fridge (savegame "Jonas-Fridge"): At first, none of the objectives was checked. Leaving the apartment or even just reloading the save will check the "Place fridge" and "Stock up" objectives, "Buy a fridge" is still not checked however. "Go to local supermarket" and "Eat some food" were done already as well, so we have to add this to the bug list (you'll find 3 food in the fridge, a 4th one I had eaten already right at the supermarket). Any of these tasks is only checked once I do it again (which is easy for the food tasks, but waste of money for the fridge).
2. Job at the supermarket (savegame Jonas-Supermarket): Just discovered a more funny issue. In order to make it easier for you, I already picked up the fridge. When I paid for it right after saving, it was registered for the objective. After reloading the save and paying, it's not registered and you need to pick up a new one.
Regarding the actual issue: After paying (and if the objective is registered), the two new objectives are still unchecked. They get checked however as soon as you leave the building, so it's similar to the two already checked objectives I mentioned in 1. - they obviously only get updated when reloading or entering/exiting a building.
Additionally, if you quit your job before leaving the building, the task is not registered. This might be intended if you want to force the user to take on a job again.
3. Bank loan (savegame Jonas-BankAndGiftshop): I already have the 15,000 loan and am running a giftshop. They're not immediately registered after you buy the fridge and leave the shop in the Jonas-Supermarket savegame; once again, on reload or entering/leaving a building, the two shop tasks are registered. The bank task is not registered.
4. Buying a mop (savegame Jonas-Mop): Once reloading, the "hire employee" and "assign employee" objectives are done, but the "buy a mop" and "clean the floors" not although both are done already. Use the mop and both objectives are checked.
5. 10 Interviews: That's actually fulfilled once you enter/exit a building, so it's the same issue like with the other objectives.

[Jonas.zip](https://github.com/hovgaardgames/bigambitions-public/files/6688837/Jonas.zip)

**Comment by jhovgaard** [comment]
Fixed in build 68
